
spring:
  level:
    root: INFO
    com.example.SBEAM: DEBUG
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/re0?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
style:
  file:
    path: dataTest/test.jsonl
dashscope:
  api-key: sk-7c04c923e64943e880ae10026b74f817
  model-endpoint: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation
  app-id: 85084d71c7d84d2fa138a5c60e8a9ea6
server:
  port: 8080
